// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription

let package = Package(
    name: "icloud-snapshot",
    platforms: [
        .macOS("12.0")
    ],
    products: [
        .executable(
            name: "icloud-snapshot",
            targets: ["icloud-snapshot"]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/apple/swift-argument-parser.git", "1.1.2"..<"2.0.0")
    ],
    targets: [
        .executableTarget(
            name: "icloud-snapshot",
            dependencies: [
                .product(name: "ArgumentParser", package: "swift-argument-parser")
            ]
        )
    ]
)
